// Deterministic, frontend-only copy — never sent to or generated by Gemini.
// Shared between OpportunityList and OpportunityDetail so the two views
// never disagree on wording. Kept in short, everyday English (Phase 8 UX
// pass) — the underlying reason/data is unchanged.
export const REASON_LABELS = {
  NO_MATCH: 'No product matched',
  OUT_OF_STOCK: 'Product was out of stock',
  INSUFFICIENT_STOCK: 'Not enough stock',
  NO_MORE_OPTIONS: 'Wanted more choices',
}

// A short advisory sentence distinct from whyExplanation (which explains WHY
// the opportunity exists) and from suggestedAction.label (a terse CTA).
export const RECOMMENDATION_TEXT = {
  NO_MATCH: 'Make a cheaper product or bundle for this.',
  NO_MORE_OPTIONS: 'Add a few more choices in this category.',
  OUT_OF_STOCK: 'Restock this to win back these sales.',
  INSUFFICIENT_STOCK: 'Increase how much you keep in stock.',
}

// Display-only mirror of the backend's own humanizeBudgetBand
// (opportunityService.js) — turns a stored band like "<=500" into the same
// short everyday phrase shown elsewhere. Never used for any calculation.
export function humanizeBudgetBand(budgetBand) {
  if (!budgetBand || budgetBand === 'none') return ''
  if (budgetBand.startsWith('<=')) return ` under ₹${Number(budgetBand.slice(2)).toLocaleString('en-IN')}`
  if (budgetBand.startsWith('>')) return ` over ₹${Number(budgetBand.slice(1)).toLocaleString('en-IN')}`
  return ''
}
