// Deterministic, frontend-only copy — never sent to or generated by Gemini.
// Shared between OpportunityList and OpportunityDetail so the two views
// never disagree on wording. Kept in short, everyday English (Phase 8 UX
// pass) — the underlying reason/data is unchanged.
export const REASON_LABELS = {
  NO_MATCH: 'No product matched',
  OUT_OF_STOCK: 'Product was out of stock',
  INSUFFICIENT_STOCK: 'Not enough stock',
  NO_MORE_OPTIONS: 'Wanted more choices',
}

// Feature 2 — frontend mirror of the backend's DRAFT_ELIGIBLE_ACTION_TYPES /
// RESTOCK_ACTION_TYPES (opportunityService.js), kept as an independent copy
// rather than shared code (same pattern already used for
// isProductPurchasable). Gates which CTA the detail page shows for
// opportunity.suggestedAction.type — the backend's deterministic
// determineAction() is the single source of truth for the type itself.
export const DRAFT_ELIGIBLE_ACTION_TYPES = ['CREATE_PRODUCT', 'CREATE_VARIANT', 'ADD_OPTION']
export const RESTOCK_ACTION_TYPES = ['RESTOCK_PRODUCT', 'INCREASE_STOCK']

// Display-only mirror of the backend's own humanizeBudgetBand
// (opportunityService.js) — turns a stored band like "<=500" into the same
// short everyday phrase shown elsewhere. Never used for any calculation.
export function humanizeBudgetBand(budgetBand) {
  if (!budgetBand || budgetBand === 'none') return ''
  if (budgetBand.startsWith('<=')) return ` under ₹${Number(budgetBand.slice(2)).toLocaleString('en-IN')}`
  if (budgetBand.startsWith('>')) return ` over ₹${Number(budgetBand.slice(1)).toLocaleString('en-IN')}`
  return ''
}
